/**
 * Session Manager for Guest User Support
 * Handles session ID storage and management
 * Note: Session ID is generated by backend and stored in httpOnly cookie
 */

const SESSION_KEY = 'guest_session_id';

/**
 * Get existing session ID from localStorage (if previously stored)
 * Session ID is primarily managed via httpOnly cookie from backend
 * @returns {string|null} Session ID if available
 */
export function getSessionId() {
    if (typeof window === 'undefined') return null;

    // Check localStorage for legacy session ID
    let sessionId = localStorage.getItem(SESSION_KEY);
    return sessionId || null;
}

/**
 * Set a new session ID (legacy support)
 * @param {string} sessionId - Session ID to set
 */
export function setSessionId(sessionId) {
    if (typeof window === 'undefined') return;
    localStorage.setItem(SESSION_KEY, sessionId);
}

/**
 * Clear the stored session (legacy support)
 */
export function clearSession() {
    if (typeof window === 'undefined') return;
    localStorage.removeItem(SESSION_KEY);
}

/**
 * Migrate session data to user account (called after login)
 * @param {string} userId - User ID to migrate to
 * @returns {Promise<Object>} Migration result
 */
export async function migrateSession(userId) {
    const sessionId = getSessionId();

    if (!sessionId) {
        return { success: false, message: 'No session to migrate' };
    }

    try {
        const response = await fetch('/api/session/migrate', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-session-id': sessionId,
            },
            body: JSON.stringify({ userId }),
        });

        const data = await response.json();

        if (data.success) {
            // Clear session after successful migration
            clearSession();
        }

        return data;
    } catch (error) {
        console.error('Session migration error:', error);
        return { success: false, message: 'Failed to migrate session' };
    }
}

/**
 * Initialize session on app load
 * Session ID is managed via httpOnly cookie from backend
 * Returns legacy stored session if available
 */
export function initializeSession() {
    return getSessionId();
}
